### ISSUE TITLE
Enforce "must pass" list of tests

### ISSUE THREAD

**Issue by akbertram** [bedatadriven/renjin-release#4]
# Introduction

The Renjin project's must pressing need is for a reliable "quality gate" to ensure that a given set of project versions - the Renjin interpreter, the build tooling, CRAN packages, and replacement pacakges work correctly together.

The Renjin interpreter (bedatadriven/renjin) itself has a test suite of 40k+ tests that are our primary quality gate, but even this large and growing suite has proved to be insufficient given the complexity and breadth of R packages and tooling.

The hundreds of thousands of tests written for CRAN and BioConductor packages are our best source of validation for Renjin's compatability with GNU R. All of these tests together would give us the confidence that Renjin functions correctly, or at least in the same way that a specific version of GNU R does. It will also allow us to move faster with Renjin development, particularly in regard to novel optimizations, by providing immediate feedback on the correctness of such optimizations.

Using "all tests must pass" as a quality gate, however, is unworkable in practice, for a number of reasons:

1. Some package tests may fail because Renjin diverges from GNU R in a way that we as Renjin developers judge to be insignificant. Think of small differences in formatting, the text of error messages, the order of attributes, but also tests that make assertions about floating point values without a tolerance to account for legitimate differences in implementation. 
2. Tests may fail because they rely on functionality that we do not plan to support in Renjin, for example, loading a native shared library at runtime, or relying on an undocumented GNU R internal function.
3. Tests may fail because they rely on functionality that is simply not finished in Renjin. Certainly the best route is to implement the required functionality, but we may wish to instead document the limitation and move forward with a release rather than delay endlessly.
4. Tests may fail (rarely) because GNU R produces an objectively incorrect result and Renjin produces an objectively correct one. 

These, it should be said, are all potential "false negatives" in a quality gate that relies on package tests. There is the course the potential for false positives. Not all package tests actually make assertions for example, so a test could complete without error and still not demonstrate that the results are correct. But false negatives are the first blocker.

# The "must-pass" list

To deal with the problem of false negatives, we need to manually or semi-manually maintain a list of "must pass" tests. I'm not sure if it's better to have a list of exemptions, or a list of tests that must pass, but the list might look something like this:

    cran:digest
    - sha1.R: floating point values are different, but within tolerances
    - crc1.R: TODO: issue #232
    cran:ggplot2 
    cran:rversions ALL PASS

Could also use a standard format like YAML or JSON, but it should be easy to edit and read.

After the build runs, a program in `tools/` should scan all the package build directories and compare the results with must-pass list. See [PackageSetup.java](https://github.com/bedatadriven/renjin-release/blob/master/tools/src/main/java/org/renjin/release/PackageSetup.java) for an example of how this might look. A pre-requisite is getting detailed output from the `testNamspaceTask`, see https://github.com/bedatadriven/renjin-gradle-plugin/issues/1.

A starting point might be simply to dump the current results and gradually chip away at the failures, adding them to the must pass list as we go.

**Comment by perNyfelt** [comment]
What about passing a system property or environment variable to gradle and then set up the subprojects based on the relevant packages.xxx file in settings.gradle?

If we add a packages.mustpass in the same format as the others we could do
gradle -Dprofile=mustpass test
or to include all in the certified suite
gradle -Dprofile=certified
etc...
it would not require to much of magic in settings.gradle to make that work. Basically just get the property, look up the correct file and parse it and then include the relevant subprojects.

**Comment by akbertram** [comment]
I think that's a good approach, as long as you add it as a second Gradle task, like "checkTests". That way you could iteratively update the must-pass list without having to rerun all the tests. You could register the results file as an output of the `testNamespace` task, and an input of the `checkTest` task, for example.

**Comment by perNyfelt** [comment]
Yes, I think I see what you are saying. 
1. We run all the tests as integration tests i.e. a failed test does not halt the build. I am not fully up to speed with the renjin-gradle-plugin but I guess you mean that the renjin-gradle-plugin can be configured so that the result for each test file is outputted to a file that we can then read. i.e. you would have quite a few test results files for each package*. 

2. We create a new checkTests task that parses all the the test results for the profile and checks against the profile file (packages.mustpass or whichever one you want to check against) and determines if a failure is really a failure or not (i.e. not regarded as failure if it has been excluded in the file (the "- testFile" notation under the package)

This way you could fix, rerun the test and then run checkTest again without having to rerun all the tests.

Was this what you had i mind?

* If it is outputting one result file for all the tests in one package it would also work but then all tests in the package would have to be rerun to create a new output file that could be read by the checkTests task.

**Comment by akbertram** [comment]
Yes, i think we are on the same page.

Our Gradle TestNamespaceTask currently has an [ignoreFailues](https://github.com/bedatadriven/renjin-gradle-plugin/blob/d74e92c2c3246a49f8dba737cb84e212f74410b1/src/main/groovy/org/renjin/gradle/TestNamespaceTask.groovy#L50) property. If this task property is set to true, then the `TestNamespaceTest` will "succeed" even if there are test failures.

The nice thing about Gradle, is that it won't repeat tasks whose declared inputs haven't changed. So if you run:

```
./gradlew cran:ada:test
```
the first time, you'll see:

```
BUILD SUCCESSFUL in 31s
8 actionable tasks: 8 executed
```
But if you run it again, you'll see:

```
BUILD SUCCESSFUL in 2s
8 actionable tasks: 8 up-to-date
```
Which indicates that Gradle didn't do any work, because neither ada's classpath changed, nor did any of its sources or test sources. As long as `ignoreFailures` is set to true, this task should always succeed.

Then, like you said, you add a new `checkTests` which depends on `testNamespaceTask` and consumes its outputs, as well as the must-pass list. If either of those have changed since the last run, then the task is executed. The task checks the list of failed tests against the must-pass list, and either "succeeds" if the check is ok, or "fails" if a test that's supposed to pass, fails.

Note that our Gradle TestNamespaceTask is not _that_ smart, if _anything_ is changed, it will re-run _all_ of the tests. I suggested splitting the testNamespace task and the checkTests task because it would save you time if you _only_ changed the must pass list.

**Comment by perNyfelt** [comment]
OK great, this clarifies things! I think I know what to do then...

**Comment by perNyfelt** [comment]
I have the first part working i.e. to run all the tests in a list e.g. .to tun the very short packages.mustpass list (which right now has matrix and digest) you do:
`./gradlew -Dprofile=mustpass runTests`
which is successful and equivalent to doing
`./gradlew cran:digest:test cran:matrix:test`

The idea I have is to have the checkTests task depend on the runTests task and consume its output as you envisioned above.

I just have a question: when i tried to run to run the tests in the packages.certified list 
`./gradlew -Dprofile=certified runTests`

it will result in a failure on testthat:compileNamespace
`Exception in thread "main" org.renjin.eval.EvalException: IOException while loading package org.renjin.cran:rlang: Exception calling rlang_library_load : Unimplemented GNU R API function 'Cannot change SEXP of type 'pairlist' to 'language''`

I understand that setting the ignoreFailures on testNamespace will allow all tests to be execute regardless of outcome. I guess that in this particular case it should fail but maybe there are more gray areas in other packages? Would it be a good idea to ignore certain compilation failures as well and then catch them in the checkTests task?

**Comment by akbertram** [comment]
Sounds good! All packages included in the master branch should now complete the compileNamespace task. We have 11 packages left that are timing out on the testNamespace task:
https://build.renjin.org/job/renjin-release/29/console

I had forgotten to include the patched version of rlang: that should now be fixed in master.
